BEGIN;

INSERT INTO stamps (id,title, content, template_id, profile_id)
VALUES 
('b0196eda-fa10-4aa3-846b-e295dc55a378','INBOUND OTHER','Contact Type: Inbound Call\nContact With: Relationship, name\nPhone: \nDetails of Conversation: TT: \nNext Steps to Advance Case:','c61b0b77-ecba-4f6b-b5e8-0b6b373809c2','520f7c5b-fba3-4d25-bc22-b8ae8fc9c475'),
('22c90fde-03b5-48b4-9503-e338940be3c4','OUTBOUND OTHER','Contact Type: Outbound Call\nContact With: Relationship, name\nPhone: \nDetails of Conversation: TT: \nNext Steps to Advance Case: ','c61b0b77-ecba-4f6b-b5e8-0b6b373809c2','520f7c5b-fba3-4d25-bc22-b8ae8fc9c475'),
('d28e1741-93bb-45ef-9401-ee1eaf23b44b','CONVERATION WITH SELLER','CONVERSATION WITH THE SELLER(s)\n-TT: \n-Phone: \n-Discussed transfer option: Yes / No\n-The customer(s) intention is to: \n-Confirmed where they are in the purchase process: \n-IS H/O making solar a contingency of the home sale: N/A / Yes / No\n-Received permission to share information: Yes/ No\n-Requested forwarding address: Yes/ No (if no did seller refuse )\n-Listing Agents contact information:\n-Discussed disconnecting SG Modem and leaving it on a counter for buyers: Yes / No\n-Pre PTO- Informed the customer that PTO has been paused : N/A / Yes / No\n-For Oregon Only - Discussed RETC and remaining balance: N/A / Yes / No\n-Informed the customer of their delinquent balance: N/A / Yes / No\n-If delinquent, informed that if not paid, it will be invoiced through escrow:  N/A / Yes/ No\n\nSummary of Call: ','c61b0b77-ecba-4f6b-b5e8-0b6b373809c2','520f7c5b-fba3-4d25-bc22-b8ae8fc9c475'),
('11f05407-422c-4b5e-827a-df38c35223ad','INTRO VM','Contact Type: Outbound Call\nContact with Seller / Buyer: \nPhone: \nLVM: For Seller/Buyer to follow up regarding the sale/purchase of the property and go over transfer Process. Left my phone number for a call back.\n \nNext Steps to Advance Case: ','c61b0b77-ecba-4f6b-b5e8-0b6b373809c2','520f7c5b-fba3-4d25-bc22-b8ae8fc9c475'),
('08cbaba0-a8b8-4af5-ac93-30a25069f0f4','LISTING AGENT','CONVERSATION WITH THE LISTING AGENT\n \n-TT (name/number): \n-Discussed Sellers intentions: yes / no\n-Discussed contingency on the home sale: yes / no\n-Discussed the Reassignment Agents role in the transfer of the solar agreement: yes / no\n-Expected COE Date:  \n-Requested the Buyers Agent contact information: \n\n-Summary of Call: ','c61b0b77-ecba-4f6b-b5e8-0b6b373809c2','520f7c5b-fba3-4d25-bc22-b8ae8fc9c475'),
('bcf4f5a1-82a2-4b08-ba73-4439bf431509','BUYERS AGENT','CONVERSATION WITH THE BUYERS AGENT\n \n-TT (name/number): \n-Confirmed where they are in the purchase process:\n-Does the Buyer have a copy of the contract: \n-Expected COE Date: \n-Requested the Buyers information: \n-Requested Escrow/Title contact information:  \n\n-Summary of Call: ','c61b0b77-ecba-4f6b-b5e8-0b6b373809c2','520f7c5b-fba3-4d25-bc22-b8ae8fc9c475'),
('71ed1d35-35ff-4ad5-afe4-cf39b7fd564f','CONVERSATION WITH BUYER','CONVERSATION WITH THE BUYER(s)\n-TT:\n-Phone: \n-Email: \n-Confirmed where they are in the purchase process: \n-Expressed the Sellers intention: \n-Expected COE Date: \n-Verified they have a copy of the contract: \n-Discussed the customers obligations: (Monthly payments, escalator, ACH and internet): \n-Discussed our obligations to the customer: (Warranty, insurance, repair promise, PeGu, etc.): \n-Discussed estimated production: \n-Discussed the transfer process: \n-Discussed the credit policy: \n-How is the title of home going to be held:  name/ trust/ LLC\n-Exact Name on title: \n-Are you on a special program with the local utility ( ex: Care/ Medical baseline etc. ): yes / no\n-If utility is MP2- advised to enroll within MP2 for NEM for a 1:1 credit: n/a / yes / no\n-Discussed that the Billing Portal is currently unavailable and ACH will need to be set up through CC: yes / no \n\n-Summary of Call: ','c61b0b77-ecba-4f6b-b5e8-0b6b373809c2','520f7c5b-fba3-4d25-bc22-b8ae8fc9c475'),
('8d2360ce-e30d-4a86-a1ed-1834742dfb36','ESCROW COE','Contact Type: Outbound Call\nTT Escrow: (Escrow/Title Agents Name)\nPhone: \nDetails of Conversation: Spoke with Escrow to confirm COE. Confirmed COE on (date) OR Extended COE to (date)\n \n(If an invoice was sent): Confirmation that payment has been sent (tracking number if applicable): \n\nNext Steps to Advance Case:  Pending COE OR Closing Case OR Pending Payment (Agent to specify: Partial Prepay/Full Prepay/RETC/Purchase)','c61b0b77-ecba-4f6b-b5e8-0b6b373809c2','520f7c5b-fba3-4d25-bc22-b8ae8fc9c475'),
('1dd9a0e8-af60-4720-b449-0494cdd38bb2','INTRO NOTE','Seller Name: \n  Phone: \n  Email: \n\nSeller Forwarding Address: \n\nListing Agent: N/A\n  Phone: \n  Email: \n\nSelling or Buyer Agent: N/A\n  Phone: \n  Email: \n\nBuyer Name: \n  Phone: \n  Email: \n\nEscrow Company: \n  Phone: \n  Email: \n\nEstimated Closing of Escrow Date: ','c61b0b77-ecba-4f6b-b5e8-0b6b373809c2','a7184ed8-3208-43e2-b59e-43a01ea112e8'),
('8f2b84c3-1d82-4d25-bfe3-f1cdeedf7113','SENT CVF FOR SIGNATURE','*CV Form Sent to Buyer via Adobe Sign.* \nChanging Flow Status to Pending Credit Approval','c61b0b77-ecba-4f6b-b5e8-0b6b373809c2','a7184ed8-3208-43e2-b59e-43a01ea112e8'),
('16af90ec-e256-4274-854e-58ad0fe1a4d8','CREDIT RESULT','CREDIT APPROVED\nBUYERNAME has been approved via soft credit check.\nContact ID: \n\nCONTACT ID CREATED \nBUYERNAME has been added as a contact.\nContact ID: \n\nCREDIT DECLINED\nBUYERNAME has been conditionally approved. The score is below our minimum of 650.\nContact ID:\n\nAction Taken:\nCreated $250 Credit Fee Inoice Case.\n\n******$250 fee will be required for this reassignment to proceed******\n\nUNABLE TO OBTAIN CREDIT\nWe were unable to approve this customer at this time.\nContact ID:\n\nAction Taken:\nFollowed up with buyer to request social security number or outside credit report.\n\nCREDIT NOT PULLED\nReceived leadership approval in mod case that we are proceeding without a credit score on file.\n******$250 fee will be required for this reassignment to proceed******\nOR\n$250 Fee Waived - Approval provided within same mod case.','c61b0b77-ecba-4f6b-b5e8-0b6b373809c2','a7184ed8-3208-43e2-b59e-43a01ea112e8'),
('3fa40b85-d74a-4906-b2f7-3f3b7939ae29','SENT TA FOR SIGNATURE','*Received Credit Contact ID - TA sent out for signature via Adobe Sign*\nChanging Flow Status to Pending Signed Transfer Agreement.\n\nContact Type: Outbound Call\nContact With Seller: \nPhone: \nForwarding address: \n\nDetails of Conversation: TT / LVM: Sent out the TA for signatures via email through Adobe Sign.\nLet the seller know to leave the SG Router that connects to the internet on a counter for the buyer to easily find it.\n\n\nContact Type: Outbound Call\nContact With Buyer: \nPhone: \n\nDetails of Conversation: TT / LVM: Sent out the TA for signatures via email through Adobe Sign.','c61b0b77-ecba-4f6b-b5e8-0b6b373809c2','a7184ed8-3208-43e2-b59e-43a01ea112e8'),
('6204f713-ae16-432e-b749-259758682c8c','RELOCATION','Subject Line->  Contract Reassignment - [INQUIRY] [STANDARD] Relocation \n\n Case Queues:\nOwner: TBA Asset Control\nSource: Internal\nQueue: System Relocation -PV\nSub Queue: 1. Project Inquiry\nStatus: Open\nFlow Status: 1a. No Work Done\nNote: Any pertinent information.\nSpecifically state in your note that this is an inquiry.\n \nCustomers Information: \n    Name(s) of customer(s) \n    Name of Primary contact: \n    Preferred phone number: \n    Preferred email address: \nListing Agents Information: \n    Name of primary contact: \n    Preferred phone number: \n    Preferred email address: \nNew Home Buyers Information: \n    Name of primary contact: \n    Phone number: \n    Email address: \nBuyers Agent Information: \n    Name: \n    Phone number: \n    Email address: \nEscrow Information : \n    Name: \n    Phone number: \n    Email address: \nDate of Close of Escrow for current home: \nDate of Close of Escrow for new home: \nAddress of new home: \nUtility District of new home: \nIs there an aerial view available? \nAre there any escalations we should know about? \nReason why new buyer did not assume the contract: \nIf new house is still under construction, did you request the blue prints? \n Explained the relocation process & associated fees to customer? \nIf system is being moved to a friend/relatives house: \n    Name of primary contact: \n        Phone number: \n        Email address: \n    Did you run credit for this person? \n    If applicant passed credit, did you add him/her to the contract? \nIs system deactivated? \nWhen was it deactivated? \nName of person currently residing in the home:','c61b0b77-ecba-4f6b-b5e8-0b6b373809c2','a7184ed8-3208-43e2-b59e-43a01ea112e8'),
('ae40e31f-ce5e-4b21-8d41-20510c820674','LENDER RELATIONS','Subject Line -> CR [FNMA] [Insurance] [FHA] [Payoff] [Billing History] [Questionnaire] [Discussion] [Golden1]\n\nOwner: Recordings\nQueue: Lender Relations\nSub Queue: Reassignment Request\n\n***Please delete above before saving note***\n\nPlease contact the party below due to Contract Reassignment\nNotes: \nName: \nRelationship: \nTelephone: \nEmail:','c61b0b77-ecba-4f6b-b5e8-0b6b373809c2','a7184ed8-3208-43e2-b59e-43a01ea112e8'),
('35d29c53-3fba-41d6-9d98-ad067f0cf49e','RELEASE UCC','Subject Line -> Reassignment - Release UCC-1\n\nTransfer Agreement received. Please send UCC release to: \n\nName: \nPhone: \nEmail: \n\nNormal Turnaround Time: 2-3 business days \nUrgent Turnaround Time: 2 hours (if submitted prior to 4pm)\n\nReason for Urgency: \n\n(Agent to Delete what doesnt apply from the above)','c61b0b77-ecba-4f6b-b5e8-0b6b373809c2','a7184ed8-3208-43e2-b59e-43a01ea112e8'),
('9d0daa91-26d7-4334-9d61-d82a3c6d3aa2','REPEASE PUC','Subject Line -> Reassignment - Release PUC\n\nTransfer Agreement received. Please send PUC release to: \n  \nName: \nPhone: \nEmail:  \nMailing Address: \n\nNormal Turnaround Time: 2-3 business days \nUrgent Turnaround Time: 2 hours (if submitted prior to 4pm)\n\nReason for Urgency: \n\n(Agent to Delete what doesnt apply from the above)','c61b0b77-ecba-4f6b-b5e8-0b6b373809c2','a7184ed8-3208-43e2-b59e-43a01ea112e8');

COMMIT;